application: luismontreal
version: 1
runtime: php
api_version: 1

handlers:
# Serve images as static resources.
#- url: /(.+\.(gif|png|jpg))$
#  static_files: \1
#  upload: .+\.(gif|png|jpg)$
#  application_readable: true

#PC Assets
- url: /pc/css
  static_dir: views/pc/assets/css

- url: /pc/js
  static_dir: views/pc/assets/js
  
- url: /pc/img
  static_dir: views/pc/assets/img

# Serve php scripts.
- url: /.*
  script: index.php
#  script: vendor/slim/slim/index.php