application: luismontreal
version: 6a
runtime: php
api_version: 1

default_expiration: "360d"

handlers:
# Serve images as static resources.
#- url: /(.+\.(gif|png|jpg))$
#  static_files: \1
#  upload: .+\.(gif|png|jpg)$
#  application_readable: true

#PC Assets

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml
  
- url: /pc/css
  static_dir: views/pc/assets/css
   
- url: /pc/js
  static_dir: views/pc/assets/js
    
- url: /pc/img
  static_dir: views/pc/assets/img
  
# Serve php scripts.
- url: /crons/.*
  script: crons.php
  
- url: /.*
  script: index.php