application: luismontreal
version: 3
runtime: php
api_version: 1

handlers:
# Serve images as static resources.
#- url: /(.+\.(gif|png|jpg))$
#  static_files: \1
#  upload: .+\.(gif|png|jpg)$
#  application_readable: true

#PC Assets

- url: /favicon.ico
  static_files: app/favicon.ico
  upload: app/favicon.ico
  
- url: /robots.txt
  static_files: app/robots.txt
  upload: app/robots.txt
  
- url: /pc/css
  static_dir: views/pc/assets/css

- url: /pc/js
  static_dir: views/pc/assets/js
  
- url: /pc/img
  static_dir: views/pc/assets/img
  
# Serve php scripts.
- url: /.*
  script: index.php
#  script: vendor/slim/slim/index.php